---
title: "Group 6/F: Process Integration and Optimization for a Dairy Factory"
editor: visual
---
# Introduction {#intro}
| Name           | Sciper |
|----------------|--------|
|  Simon BRUNO   | 310348 |
| Corentin JAIRE | 310573 |
|  Lina KUHLMANN | 312893 |
| Lorenzo PRECHT | 310969 |
| Valentine REHN | 342655 |

The dairy industry, like many others, confronts challenges related to efficiency and sustainability. As part of the "ME-451 Advanced Energetics 2023/2024" course, a project has been initiated to address these challenges through a case study.
Mrs. Pacometer, the owner of a dairy processing facility, recognizing the need for improvements in both energy and economic efficiency, approached PinchSim (us) to conduct a comprehensive study. The key processes within her dairy factory that will be subject to analysis include Milk Pasteurization, Milk Evaporation, Drum Dryers, Cleaning in Place, Cold Storage and Hot Water, Wastewater and Sludge Production, Rivella, and Digester. The study encompasses a range of tasks, including the determination of mass and energy balances, exergy analysis, implementation of an energy bill, identification of pinch points, heat exchanger network design. and optimization of utility integration, among others.

In the pursuit of efficiency improvements, Mrs. Pacometer attended an industrial round-table where strategies for cost reduction and income generation were discussed. Two particularly intriguing propositions emerged to boost income. Mr. Rivella proposed utilizing surplus whey to produce the iconic Swiss drink Rivella, while Mrs. Green suggested the use of both whey and sludge for biogas production. The goal of this study is to assess the viability of these innovative ideas and determine if they indeed contribute to the objectives of Mrs. Pacometer and reduce the total costs.

All in all, the study aims to propose modifications based on the results of the analysis, with a focus on optimizing processes, introducing innovative co-products, and evaluating the integration of energy-efficient technologies. The ultimate objective is to provide Mrs. Pacometer with insights that will not only enhance the efficiency of her dairy processing facility but also contribute to the industry's overall sustainability and economic viability.
