```{python loadingdata, echo = T, eval = T}
#Load csv files (dfevap, dfhx, dfrecap)
import pandas as pd
import numpy as np
#Load csv files
dfevap = pd.read_csv('dfevap.csv', sep = ',')
dfhx = pd.read_csv('dfhx.csv', sep = ',')
dfrecap = pd.read_csv('dfrecap.csv', sep = ',')
```

```{python evap, echo = T, eval = T}
```
# Exergy analysis and Energy bill

## Exergy analysis

To evaluate the losses and inefficiencies in the dairy production, an exergy analysis is performed. An exergy loss is the difference between the exergy entering a uunit and the exergy leaving the unit. This exergy analysis includes calculating heat losses for each component experiencing heat transfer, covering both pasteurization and evaporation processes. The ambient temperature is set at $T_a = 25°C + 273K = 293K$.

### Pasteurization

#### Refrigeration

$$
L_{milk\_ref} = \dot{m}_{f\_milk}c_{p_{f\_milk}}\left((T_{f\_milk} - T_{mixure\_out}) - T_a \ln\left(\frac{T_{f\_milk}}{T_{mixure\_out}}\right)\right)
$$
$$
L_{gly\_ref} = \dot{m}_{gly\_ref}c_{p_{glywater}}\left((T_{f\_milk} - T_{mixure\_out}) - T_a \ln\left(\frac{T_{f\_milk}}{T_{mixure\_out}}\right)\right)
$$
$$
L_{ref} = L_{milk\_ref} + L_{gly\_ref}
$$

#### Past 1
$$
L_{past1\_1} = \dot{m}_{f\_milk}c_{p_{f\_milk}}\left((T_{mixure\_out} - T_{past\_cent}) - T_a \ln\left(\frac{T_{mixure\_out}}{T_{past\_cent}}\right)\right)
$$
$$
L_{past1\_2} = \dot{m}_{milk}c_{p_{raw\_milk}}\left((T_{past\_c} - T_{past\_d}) - T_a \ln\left(\frac{T_{past\_c}}{T_{past\_d}}\right)\right)
$$
$$
L_{past1} = L_{past1\_1} + L_{past1\_2}
$$

#### Past 2
$$
L_{past2\_1} = \dot{m}_{milk}c_{p_{raw\_milk}}\left((T_{milk\_0} - T_{past\_a}) - T_a \ln\left(\frac{T_{milk\_0}}{T_{past\_a}}\right)\right)
$$
$$
L_{past2\_2} = \dot{m}_{milk}c_{p_{raw\_milk}}\left((T_{past\_b} - T_{past\_c}) - T_a \ln\left(\frac{T_{past\_b}}{T_{past\_c}}\right)\right)
$$
$$
L_{past2} = L_{past2\_1} + L_{past2\_2}
$$

#### Past 3
$$
L_{past3\_1} = \dot{m}_{milk}c_{p_{raw\_milk}}\left((T_{past\_a} - T_{past\_b}) - T_a \ln\left(\frac{T_{past\_a}}{T_{past\_b}}\right)\right)
$$

$$
L_{past3\_2} = \dot{m}_{steam\_past3}c_{p_{steam}} \Delta h_3 - T_a \Delta s_3
$$
$$
L_{past3} = L_{past3\_1} + L_{past3\_2}
$$

#### Past 4

$$
L_{past4\_1} = \dot{m}_{milk}c_{p_{raw\_milk}}\left((T_{past\_d} - T_{milk}) - T_a \ln\left(\frac{T_{past\_d}}{T_{milk}}\right)\right)
$$
$$
L_{gly\_past4} = \dot{m}_{gly\_past4}c_{p_{glywater}}\left((T_{past\_d} - T_{milk}) - T_a \ln\left(\frac{T_{past\_d}}{T_{milk}}\right) \right)
$$
$$
L_{past4} = L_{past4\_1} + L_{gly\_past4}
$$

#### Past 5
$$
L_{past5\_1} = \dot{m}_{int}c_{p_{cream}}\left((T_{cream} - T_{crpast\_a}) - T_a \ln\left(\frac{T_{cream}}{T_{crpast\_a}}\right)\right)
$$
$$
L_{past5\_2} = \dot{m}_{cream}c_{p_{cream}}\left((T_{crpast\_b} - T_{crpast\_c}) - T_a \ln\left(\frac{T_{crpast\_b}}{T_{crpast\_c}}\right)\right)
$$
$$
L_{past5} = L_{past5\_1} + L_{past5\_2}
$$

#### Past 6
$$
L_{past6\_1} = \dot{m}_{cream}c_{p_{cream\_mixed}}\left((T_{crpast\_x} - T_{crpast\_b}) - T_a \ln\left(\frac{T_{crpast\_x}}{T_{crpast\_b}}\right)\right)
$$
$$
L_{past6\_2} = \dot{m}_{steam\_past6}c_{p_{steam}} \Delta h_6 - T_a \Delta s_6
$$
$$
L_{past6} = L_{past6\_1} + L_{past6\_2}
$$

#### Past 7

$$
L_{past7\_1} = \dot{m}_{cream}c_{p_{cream}}\left((T_{crpast\_c} - T_{cream}) - T_a \ln\left(\frac{T_{crpast\_c}}{T_{cream}}\right)\right)
$$
$$
L_{gy\_past7} = \dot{m}_{gly\_past7}c_{p_{glywater}}\left((T_{crpast\_c} - T_{cream}) - T_a \ln\left(\frac{T_{crpast\_c}}{T_{cream}}\right)\right)
$$
$$
L_{past7} = L_{past7\_1} + L_{gy\_past7}
$$

#### Mixer

$$
L_{mixer\_1} = \dot{m}_{cream}c_{p_{cream}}\left((T_{crpast\_a} - T_{crpast\_x}) - T_a \ln\left(\frac{T_{crpast\_a}}{T_{crpast\_x}}\right)\right)
$$
$$
L_{mixer\_2} = \dot{m}_{thick}c_{p_{alboline}}\left((T_{thick} - T_{crpast\_x}) - T_a \ln\left(\frac{T_{thick}}{T_{crpast\_x}}\right)\right)
$$
$$
L_{mixer} = L_{mixer\_1} + L_{mixer\_2}
$$



#### Summary of Pasteurization Exergy Results

```{python compute_pasteurisation, echo = T, eval = T}

#Exergy Pasteurization

import math
import pandas as pd
import numpy as np
from IPython.display import display, HTML

df = pd.read_csv('pasteurization_process.csv',sep = ';')

for i in range(0,len(df.index)):
    globals()[df.iloc[i][1]] = df.iloc[i][2]

Delta_T_Gly=5
Ta=298

#Refrigeration
L_milk_ref=m_fmilk*Cp_fmilk*((T_fmilk-T_mixure_out)-T_a*math.log(T_fmilk/T_mixure_out))

L_gy_ref=m_gly_ref*Cp_glywater*((T_fmilk-T_mixure_out)-T_a*math.log(T_fmilk/T_mixure_out))#glywater temperature

L_ref=L_milk_ref+L_gy_ref
#print(L_ref)

#Past 1

L_past1_1=m_fmilk*Cp_fmilk*((T_mixure_out-T_past_cent)-T_a*math.log(T_mixure_out/T_past_cent))
L_past1_2=m_milk*Cp_raw_milk*((T_past_c-T_past_d)-T_a*math.log(T_past_c/T_past_d) )

L_past1=L_past1_1+L_past1_2
#print(L_past1)
#Past 2

L_past2_1=m_milk*Cp_raw_milk*((T_milk_0-T_past_a)-T_a*math.log(T_milk_0/T_past_a)) #Question which m and cp
L_past2_2=m_milk*Cp_raw_milk*((T_past_b-T_past_c)-T_a*math.log(T_past_b/T_past_c))#Question which m and cp

L_past2=L_past2_1+L_past2_2
#print(L_past2)

#Past 3

L_past3_1=m_milk*Cp_raw_milk*((T_past_a-T_past_b)-T_a*math.log(T_past_a/T_past_b))
L_past3_2=m_steam_past3*Cp_steam*delta_h_steam-T_a*delta_s_steam

L_past3=L_past3_1+L_past3_2
#print(L_past3)

#Past 4

L_past4_1=m_milk*Cp_raw_milk*((T_past_d-T_milk)-T_a*math.log(T_past_d/T_milk))

L_gy_past4=m_gly_past4*Cp_glywater*((T_past_d-T_milk)-T_a*math.log(T_past_d/T_milk))#glywater temperature

L_past4=L_past4_1+L_gy_past4
#print(L_past4)

#Past 5
L_past5_1=m_int*Cp_cream*((T_cream-T_crpast_a)-T_a*math.log(T_cream/T_crpast_a))
L_past5_2=m_cream*Cp_cream*((T_crpast_b-T_crpast_c)-T_a*math.log(T_crpast_b/T_crpast_c))

L_past5=L_past5_1+L_past5_2
#print(L_past5)

#Past 6
L_past6_1=m_cream*Cp_cream_mixed*((T_crpast_x-T_crpast_b)-T_a*math.log(T_crpast_x/T_crpast_b))
L_past6_2=m_steam_past6*Cp_steam*delta_h_steam-Ta*delta_s_steam

L_past6=L_past6_1+L_past6_2
#print(L_past6)

#Past 7

L_past7_1=m_cream*Cp_cream*((T_crpast_c-T_cream)-T_a*math.log(T_crpast_c/T_cream))

L_gy_past7=m_gly_past7*Cp_glywater*((T_crpast_c-T_cream)-T_a*math.log(T_crpast_c/T_cream))#glywater temperature

L_past7=L_past7_1+L_gy_past7
#print(L_past7)

#Mixer

L_mixer_1=m_cream*Cp_cream*((T_crpast_a-T_crpast_x)-T_a*math.log(T_crpast_a/T_crpast_x))
L_mixer_2=m_thick*Cp_alboline*((T_thick-T_crpast_x)-T_a*math.log(T_thick/T_crpast_x))

L_mixer=L_mixer_1+L_mixer_2
#print(L_mixer)

#Total exergy pasteurisation section

L_tot_past= L_ref+L_past1+L_past2+L_past3+L_past4+L_past5+L_past6+L_past7+L_mixer
#print(L_tot_past)

# Dataframe for Exergy Loss Pasteurization

Exergy_losses  = 'W'

Variables_Names = ['L_Refrigeration','L_Past1','L_Past2','L_Past3','L_Past4','L_Past5','L_Past6','L_Past7','L_mixer','L_tot_past']
Variables_Values = np.divide([L_ref,L_past1,L_past2,L_past3,L_past4,L_past5,L_past6,L_past7,L_mixer,L_tot_past],1000)
Variables_Units =  Exergy_losses
df = pd.DataFrame(data = {'Exergy loss': Variables_Names, 'Value':Variables_Values, 'Unit': Variables_Units})

HTML(df.to_html(index=False))

```


### Evaporation 

#### Heat Exchanger

$$\dot{L}_{HX}=\dot{m}_{water}(h_{fg}-T_{a}s_{fg})-Q_{HX}(1-\frac{T_{a}}{T_{c,lm}})$$

#### Heat Evaporator

$$\dot{L}_{evaporator}=\dot{m}_{milk}(h_{milk,in}-h_{milk,out})-\dot{m}_{milk}T_{a}(s_{milk,in}-s_{milk,out})-\dot{m}_{water}Cp_{water}[T_{out}-$$

#### Splitter
There are no exergy losses in the spliiters since they are isenthalpic


#### Total

$$\dot{L}_{evaporation}=\Sigma\dot{L}_{HX}+\Sigma\dot{L}_{evaporator}+\Sigma\dot{L}_{splitter}$$


#### Results Exergy Analysis Evaporation

```{python HX, echo = T, eval = T}

#Exergy Evaporation

import math
import pandas as pd
import numpy as np
from IPython.display import display, HTML



#Load csv files (dfevap, dfhx, dfrecap)
#import pandas as pd
#import numpy as np
#Load csv files

#dfevap = pd.read_csv('dfevap.csv', sep = ',')
#dfhx = pd.read_csv('dfhx.csv', sep = ',')

dfrecap = pd.read_csv('dfrecap.csv', sep = ',')

for i in range(0,len(dfrecap.index)):
    globals()['m'+str(i+1)] = dfrecap['Mass flow (kg/s)'].iloc[i]
    globals()['h'+str(i+1)] = dfrecap['Enthalpy (J/mol)'].iloc[i]
    globals()['s'+str(i+1)] = dfrecap['Entropy (J/K)'].iloc[i]


#Exergy for heat exchangers

Ta=298

L_heat1 = m11*(h11-Ta*s11)-m12*(h12-Ta*s12)+m1*(h1-Ta*s1)-m2*(h2-Ta*s2)
#print(L_heat1)

L_heat2= m2*(h2-Ta*s2)-m3*(h3-Ta*s3)+m16*(h16-Ta*s16)
#print(L_heat2)

L_heat3=m3*(h3-Ta*s3)-m4*(h4-Ta*s4)+m20*(h20-Ta*s20)
#print(L_heat3)

L_heat4=m4*(h4-Ta*s4)-m5*(h5-Ta*s5)-m15*(h15-Ta*s15)
#print(L_heat4)

#Exergy for evaporators

L_eva1=m6*(h6-Ta*s6)-m7*(h7-Ta*s7)-m14*(h14-Ta*s14)+m21*(h21-Ta*s21)
#print(L_eva1)

L_eva2=m8*(h8-Ta*s8)+m17*(h17-Ta*s17)-m15*(h15-Ta*s15)-m9*(h9-Ta*s9)
#print(L_eva2)

L_eva3=m10*(h10-Ta*s10)-m18*(h18-Ta*s18)-m19*(h19-Ta*s19)-m11*(h11-Ta*s11)


#Total exergy evaporation section

L_tot_eva= L_heat1+L_heat2+L_heat3+L_heat4+L_eva1+L_eva2+L_eva3
#print(L_tot_eva)

# Dataframe for Exergy Loss Evaporation

Exergy_losses  = 'W'

Variables_Names = ['L_heat1','L_heat2','L_heat3','L_heat4','L_eva1','L_eva2','L_eva3','L_tot_eva']
Variables_Values = np.divide([L_heat1,L_heat2,L_heat3,L_heat4,L_eva1,L_eva2,L_eva3,L_tot_eva],1000)
Variables_Units =  Exergy_losses
df_2 = pd.DataFrame(data = {'Exergy loss': Variables_Names, 'Value':Variables_Values, 'Unit': Variables_Units})

HTML(df_2.to_html(index=False))
```

```


Furthermore, we highly encourage the use of a Sankey diagram to succinctly summarize your findings. We have provided an example of how to create an interactive Sankey diagram in R using the Plotly library. You can access the necessary function in the file `./sankey_ipese.R`. The following code chunk demonstrates how to utilize this function:

```{r sankey-function, echo = T, eval = T, warning = F, message=F}
source("./sankey_ipese.R") # introduce the sankey function from the source file
df = read.csv('atom_balance.csv',sep = '\t') # replace the atom_balance.csv with your exergy analysis results
sankey_ipese(df = df, unit = 'kmol/h', title = 'Example of an interactive Sankey diagram') # replace the unit and title here
```

## Energy bill

> **Task Instructions**
>
>In this section, your objective is to transform the energy demand you previously calculated into utility consumption. This transformation involves the following energy vectors:
>
>- Natural gas
>- Electricity
>- Water
>
>To execute this conversion, you must explicitly state the assumptions you make during the process. For example, if you are aware of the refrigeration duty within the factory and understand that the refrigeration system operates on electricity, you will pre-determine the coefficient of performance (COP) for your refrigeration cycle. This assumption will enable you to calculate the actual electricity consumption for your processes.
>
>You can refer to the "Brewery example" in the Suivival Guide for comprehensive guidance and relevant information to facilitate this conversion process.
>
>Once you have established the energy utility demand within the dairy factory, you can proceed to calculate the energy bill. This calculation will be based on assumptions regarding energy prices in different countries or regions.

First, the price of electricity (@noauthor_electricity_nodate) and natural gas (@noauthor_natural_nodate) in France and Germany has to be determined. 

```{python Price Table, echo = T, eval = T}
#print dataframe with the price of electricity and natural gas in France and Germany
import pandas as pd
import numpy as np
from IPython.display import display, HTML

elec_fr = 0.12 # €/kWh
elec_ger = 0.21 # €/kWh
gas_fr = 0.08 # €/kWh
gas_gr = 0.08 # €/kWh

price = pd.DataFrame({'France (€/kWh)':[elec_fr, gas_fr], 'Germany (€/kWh)':[elec_ger, gas_gr]}, index = ['Electricity', 'Natural gas'])
price = price.round(3)
HTML(price.to_html())
```

Now, let list all the assumptions used to computed the energy bill:

- The factory is running 95% of the time (8322 hours per year)
- COP of the refrigeration system is 3.5
- All water is used in closed loop. The cost is not taken into account in OPEX but will be in CAPEX.

|                     |            Heating            |           Cooling           |
|:-------------------:|:-----------------------------:|:---------------------------:|
|    Pasteurization   |        Qpast_3, Qpast_6       | Qpast_ref, Qpast_4, Qpast_5 |
|     Evaporation     |           Qevap_st1           |           Qevap_5           |
|        Dryer        |       Qdry_hx1, Qdry_hx2      |          Qdry_cool          |
|       Cleaning      |          Qclean_heat          |         Qclean_cool         |
| Storage & hot water |           Qhot_water          |          Q_storage          |
|       Rivella       |         Qrivella_heat         |                             |
|       Digester      | Qdigester_dq, Qdigester_steam |                             |

The electricity consumption for cooling is computed as follow:

$$
Elec(kW)= Q(kW) / COP
$${#eq-cool_elec}

The OPEX cost is computed as follow:

$$
OPEX(M€/y)= Q(kW) \cdot t_{\text{op}} (h/y) \cdot price(€/kWh) \cdot 10^{-6} (M€/€)
$${#eq-opex}

```{python Energy Bill, echo = T, eval = T}
top = 24*0.95*365 #h/year

#Pasterization
Qpast_ref = 60416 #W    
Qpast_4 = 3863424 #W  #A changer 
Qpast_5 = 16344 #W    #A changer
Qpast_3 = 285.76 #W   #A changer
Qpast_6 = 16643 #W    #A changer

Qpast_cool = Qpast_ref + Qpast_4 + Qpast_5
Qpast_heat = Qpast_3 + Qpast_6 

#Evap
Qevap_5 = 55703.14  #W
Qevap_st1 = 98038.87 #W
Qevap_cool = Qevap_5
Qevap_heat = Qevap_st1

#Dryer
Qdry_cool = 15299.94 #W
Qdry_hx1 =  112.16 #W
Qdry_hx2 =  1967.71#W
Qdry_cool = Qdry_cool
Qdry_heat = Qdry_hx1 + Qdry_hx2 

#Cleaning
Qclean_cool = 225940 #W
Qclean_heat = 334710 #W

#Storage & hot water
Q_storage = 500000  #W
Qhot_water = 167253.2 #W

#Rivella
Qrivella_heat =  579418.2 #W

#Digester
Qdigester_dq1 = 28754.1 #W
Qdigester_steam = 107608.5 #W
Qdigester_heat = Qdigester_dq1 + Qdigester_steam

#Cool cost
COP = 3.5 # assumption
Qcool_tot = (Qpast_cool + Qevap_cool + Qdry_cool + Qclean_cool + Q_storage)/COP
OPEXcool_fr = Qcool_tot*0.001 * elec_fr * top
OPEXcool_ger = Qcool_tot*0.001 * elec_ger *top

#Heat cost
Qheat_tot = Qpast_heat + Qevap_heat + Qdry_heat + Qclean_heat + Qhot_water + Qrivella_heat + Qdigester_heat
OPEXheat_fr = Qheat_tot*0.001 * gas_fr * top
OPEXheat_ger = Qheat_tot*0.001 * gas_gr * top

#print in a dataframe the OPEX line: cooling, heating and total and column: France, Germany
OPEX = pd.DataFrame({'France (M€/y)':[OPEXcool_fr/1e6, OPEXheat_fr/1e6, OPEXcool_fr/1e6 + OPEXheat_fr/1e6], 'Germany (M€/y)':[OPEXcool_ger/1e6, OPEXheat_ger/1e6, OPEXcool_ger/1e6 + OPEXheat_ger/1e6]}, index = ['Cooling', 'Heating', 'Total'])
OPEX = OPEX.round(3)
HTML(OPEX.to_html())
```
