# Conclusions

The objective of this project was to analyze the dairy processing facility of Mrs. Pacometer and offer recommendations for improvements in both energy and economic efficiency. Additionally, the goal was to provide advice on possibilities to enhance income, with two options under consideration: collaborating with Mr. Rivella or Mrs. Green. Mr. Rivella suggested utilizing surplus whey for the production of the iconic Swiss drink Rivella, while Mrs. Green proposed using both whey and sludge for biogas production. The study aims to assess the viability of these innovative ideas and determine if they contribute to Mrs. Pacometer's objectives and reduce total costs.

To gain a comprehensive understanding of the processes within the dairy factory, the initial objective involved determining the thermodynamic properties essential for calculating heat and mass flows in each subsystem. These calculations played a pivotal role in establishing foundational parameters crucial for the subsequent analysis of the systems. Particular emphasis was placed on two key areas: the pasteurization section, responsible for transforming fresh milk into pasteurized milk and cream, and the evaporation section, tasked with evaporating pasteurized milk to concentrated milk with a higher fat percentage. Additionally, the drum dryers section, used for transforming concentrated milk into powder, and the Cleaning in Place section, dedicated to cleaning interior surfaces of pipes, vessels, filters, and more, were analyzed. Furthermore, the Cold Storage & Hot Water section, integral for temperature control within the processes, was thoroughly examined, and attention was directed towards analyzing wastewater and sludge production. As one of the main goals of the whole project is to evaluate the collaboration with Mr. Rivella and Mrs. Green, the properties of the Rivella production and Digester section were also analyzed in detail.

Based on the analysis of each of these sections and the determination of all the thermodynamic properties, the next task was to analyze the efficiency of the pasteurization and the evaporation sections. The efficiency was assessed by conducting an exergy analysis, i.e., calculating the exergy losses of each system. The results showed that in both processes, the exergy losses are indeed crucial, indicating a relatively low energy efficiency of the entire factory. In addition, the energy bill of the dairy factory was calculated, with operating costs (OPEX) dependent on both the heating and cooling demand and the price of the utility. It was found that the OPEX for France is 1.43 M€/year, and for Germany, it is 1.68 M€/year.

The next part focused on the optimization of the heat exchangers. By refining the minimum temperature difference, the aim was to enhance heat transfer efficiency and reduce the energy bill. This method resulted in a reduction of costs (compared to the non-optimized case) for the scenarios of Past 5 as well as Pasteurization with additional heat recovery. However, the combination of Past 1 and Past 5 did not improve efficiency, and the heat recovery in Cleaning in Place reduced costs slightly in Germany but not in France.

Following this, the principles of pinch point analysis were applied, and hot and cold composite curves, as well as grand composite curves, were created. This analysis was crucial in determining the factory’s minimum energy requirement (15873 kW), maximum heat recovery potential (27013 kW), and a pinch temperature of 67 degrees.

After determining the pinch point, the goal was to design the Heat Exchanger Network (HEN). The objective of the HEN design was to use the minimum number of heat exchangers to achieve the maximum heat recovery processes. Since Mrs. Pacometer did not want to change the whole layout of the factory, only penalizing heat exchangers were considered, identified for all the systems by differentiating between four types. By defining hot and cold flows, the HEN was designed and optimized using path and loop following methods. It was interesting to observe that the path method increased the operating price and reduced the investment price, whereas the loop method reduced the operating price and increased the investment price.

The last task was to close the energy balance of the process system by supplying the needed utilities (either hot or cold) through various heating and cooling technologies. The cases analyzed were: Without Rivella + Digester, With Rivella, With Digester, and With Rivella + Digester. By using ROsmose, it was possible to determine for each of the four cases the "best" combination of utilities and their required sizes. Technologies analyzed included cooling tower, boiler, cogeneration engine, heat pump, and refrigeration. To characterize the relevance of the system, different costs (OPEX, CAPEX, ENVEX, TOTEX) were calculated. By adding the utilities to the Grand Composite Curves, it was found that cogeneration engine, heat pump, refrigeration, and cooling tower are necessary to optimize exergy losses, while a boiler is not needed.

Finally, by comparing the TOTEX for the four different cases, it was found that adding Rivella to the system would significantly reduce costs, as substantial income could be generated by selling Rivella. However, incomes from biogas were very low in comparison, and therefore, the Digester would not reduce overall costs. The overall recommendation for Mrs. Pacometer is, therefore, to start a collaboration with Mr. Rivella.


# References {-}

::: {#refs}
:::
